#!/bin/sh

# Set these paths appropriately

BIN=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/bin
CMD=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/cmd
LIB=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/latin-abbreviations
PARFILE=${LIB}/latin.par
MWLFILE=${LIB}/latin-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

