#!/bin/sh

# Set these paths appropriately

BIN=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/bin
CMD=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/cmd
LIB=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations-utf8
PARFILE=${LIB}/german-utf8.par
LEXFILE=${LIB}/german-lexicon-utf8.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
