#!/bin/sh

# Set these paths appropriately

BIN=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/bin
CMD=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/cmd
LIB=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/lib

TOKENIZER=${BIN}/separate-punctuation
SPLITTER=${CMD}/portuguese-splitter.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations-utf8
POST_TAGGING=${CMD}/portuguese-post-tagging
PARFILE=${LIB}/portuguese-finegrained-utf8.par

# splitting 
$SPLITTER $* |
# pre-tokenization
sed "s/\([\)\"\'\?\!]\)\([\.\,\;\:]\)/ \1 \2/g" |
# tokenizing
$TOKENIZER +1 +s +l $ABBR_LIST |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $PARFILE -token -lemma -sgml | 
$POST_TAGGING -yes
