#!/bin/sh

# Set these paths appropriately

BIN=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/bin
CMD=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/cmd
LIB=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
