#!/bin/sh

# Set these paths appropriately

BIN=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/bin
CMD=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/cmd
LIB=/mnt/Windows/Users/Thibault/OneDrive/Cours/Polytech/ET4/S8/TAL/Projet/Ressources/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
